language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: naqCuJve46Z6ClNb9WraI45HfZRXof5ZIJXtwX11vu0eDgE0t23cJuA1ejbcCgvNmkGDODQ49wmb8Rw+jNpyeQvJw1aYftf1ZC/YAvRRUCNl6GZujF2C138R9xXPZ1kefbxuHOiLnQUIcYofUijZ708lYSrRTdJTJbk4/YDn4RAqjFsj7jIy5ttPYRENWSasJi/JdFYjlh0mAzpBwQT7+6w9reY5mgAr5J/7ZGCFyfZEDhSu/JkoRS/hhL5i/uCrUwi6RHvV4jY5tRb/N/pnkN9jz8F6mtydfQd/JK+beqP71te/12goeBrXPgmLF1ucYeaCc9A0iGVQyOd19C3AgvprdZiPlli2VOReB5Y6zyRLy7/ovJkTGyxuX+QfOv/5fNKoSLlc91BgmnUkH3KzgcK3Hp+++zPDQgOaVOkeT6go6gsuRzrUc6KlHhLh/VAc0F8N/8oLM/AhmkhcAR+eGF4QL0gAIrRWd2sq7w1OQLROBCEJ5jBzzmzI3htoTDmMyzq5SyY7zYPK4lGv+aWRrQTEZlO19u+ZFXN/PIM667cklK0+J4UyYCtz9Pb2poiZDr5FWOoc3ZaPEstHTf+Ok0k8LiaQkuVjMm19pM70TqbgT88nZWPtjtCY1xZN7jaAnAyQdQ1Q2OUx4H2vIFQauznAyofQLeSev75zH862dV8=

install:
- npm run build
